### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by harpreet009** [jschiefner/advanced-brightness-slider-tweak#1]
Not working on iPhone XS Max iOS 14.3. 
tweaks do nothing please fix this, because this is very good tweak I love the concept. Thanks you for putting effort to create this tweak.

**Comment by Taitanoboa** [comment]
Me too, doesn’t work on XsMax iOS14.1
Great concept, could be better if intergrate function like “adaptive dark mode”.

**Comment by jschiefner** [comment]
Hi thanks to both of you reporting this issue and your kind words! I really want this to work for everyone, unfortunately i only have a single device i can test this on but i'll try everything to make it work for you. Would you mind checking in the settings app if the tweak is set to `enabled`? Or if the preferences for `AdvancedBrightnessSlider` even load? That should give at least a small hint at to what could be the problem. If the preference bundle loads correctly, maybe drag the brightness slider down completely and check if the `reduce white point` option in the Accessibility settings turned on or not for now. I will ask around if there are people who can test the tweak and supply the error message to me so i can work with that. Does either of you have a mac? There is an easy way to extract Log messages from the iPhone, allowing me to understand why the tweak is not working.

**Comment by jschiefner** [comment]
Other devs helped me figure out the issue actually. I forgot to properly initialize the preferences, making the tweak think it was disabled by the user after installing it. It would be great if you could update the tweak to version 0.1.1 and report back if that fixes your issue 🙏🏼

**Comment by Taitanoboa** [comment]
Thank you, it just works like magic.
Problem solved🙏

发自我的iPhone

**Comment by jschiefner** [comment]
Love to hear it 😊  thanks again to both of you for reporting this, without this issue i probably wouldn't have realised for a while. Enjoy the tweak and if there is anything else let me know!

**Comment by harpreet009** [comment]
Yeah, thanks you so much. It’s working great now. I would love to have more tweaks made by you like this.

**Comment by harpreet009** [comment]
Can you make a tweak ( just a idea) keep music playing through respring, other tweaks not work properly or create errors with music app after respring.

**Comment by jschiefner** [comment]
Thanks for your compliment! 😊  That sounds like a great idea, i doubt that this would be possible ssadly, because tweaks are stopped and restarted upon a respring. To my understanding this makes it impossible for code that is injected into iOS continuously running during a respring unfortunately.

**Comment by rastafaa** [comment]
> Can you make a tweak ( just a idea) keep music playing through respring, other tweaks not work properly or create errors with music app after respring.

There’s a tweak that does that already. I don’t currently use it but it worked perfectly when I tried it in the past. I think it was Resume tweak made by smokin1337
