### ISSUE TITLE
Request | Official Rootless Support?

### ISSUE THREAD

**Issue by NotDarkn** [jschiefner/advanced-brightness-slider-tweak#10]
Hi! In the past, many tweaks have been updated for rootless and one of these tweaks was Cephei Tweak Support. If I can recall, Cephei was one of the dependencies that needed to be updated for rootless in order for AdvancedBrightnessSlider to also support rootless. Now that Cephei has been updated for rootless, will this tweak be updated for rootless?

**Comment by jschiefner** [comment]
I will try to make it work, i don't have time for it right now but i'm planning to get around to in the next couple of weeks. stay tuned!

**Comment by jschiefner** [comment]
@NotDarkn i compiled a rootless version, could you try it out? You can get it here: https://uni-muenster.sciebo.de/s/HinSUN6aZDbs6R0

**Comment by jschiefner** [comment]
Perfect, thanks! I'll release it in the coming days then 🙏

**Comment by jschiefner** [comment]
@NotDarkn could you for good measure test this version as well? https://uni-muenster.sciebo.de/s/f4WL8cK5sNMvp5W it is the release version built on github actions

**Comment by jschiefner** [comment]
Released in [v1.2.1](https://github.com/jschiefner/advanced-brightness-slider-tweak/releases/tag/v1.2.1).
