### ISSUE TITLE
cannot restore default system setting after uninstall the tweak. 

### ISSUE THREAD

**Issue by FlynnYork** [jschiefner/advanced-brightness-slider-tweak#5]
cannot restore default system setting after uninstall the tweak. I can feeling it is still working when slide brightness toggle.  

unintsalled tweak, (Set system Display & Text Size, Reduce White Point to off, Auto-Brightness to off.)
when I slide to lowest point,  "Reduce White Point" auto turn on.
when I unlock screen, "Auto-Brightness" auto turn on.

My eyes are very uncomfortable. It has been more than two months and I am troubled by this problem.
Please help me fix it.

**Comment by jschiefner** [comment]
Hi! This sounds like the tweak did not get uninstalled properly. When it is properly uninstalled it is not possible that it still interferes in the system like that, because tweaks are loaded at runtime and do not change any code in a persistent way. Can you double check it is really gone from your device? Maybe it does not show up in Cydia anymore but the dylib is still being loaded?

**Comment by FlynnYork** [comment]
THX.
System. IOS 14.2
Jailbreak by Taurine
Download latest version 1.1.0. 

Auto-Brightness is working as usual now without using toggle slider. whenever unlock screen, or turn off Auto Brightness.

But sadly, it's still working with toggle slider after uninstalled it by Sileo. (then search all file which named advancedbrightnessslider and delete with filza).
I found that slider stop at the 30% posion after unstall or disable the tweak.
Before slide it status (Reduce White Point and Auto-Brightness are turn off.)
Then,
slide lower than 30% posion, educe White Point reduce is on.
slide higher than 30% posion, Auto-Brightness is on.

**Comment by jschiefner** [comment]
Hey, sorry but there is nothing that I could reset. Did you try safe mode?

**Comment by FlynnYork** [comment]
> Hey, sorry but there is nothing that I could reset. Did you try safe mode?

safe mode is working ok. 👍

**Comment by jschiefner** [comment]
Ok that means the tweak did no permanent damage to your system. If everything else fails I suggest you try to remove the jailbreak and re-jailbreak after that

**Comment by FlynnYork** [comment]
> Ok that means the tweak did no permanent damage to your system. If everything else fails I suggest you try to remove the jailbreak and re-jailbreak after that

do you mean that restore RootFS then Jailbreak again?

**Comment by jschiefner** [comment]
Yes, exactly.

**Comment by FlynnYork** [comment]
thank you! :octocat:
